language: php

php:
  - 8.1
  - 8.0
  - 7.4
  - 7.2
  - 5.6
  - 5.5
  - 5.4

before_script:
  - composer self-update
  - composer install

script:
  - phpunit --coverage-text

matrix:
  allow_failures:
    - php: 5.4